from turtle import *
tu = Turtle()
tu.screen.bgcolor("#e3f2fd")
tu.speed("fast")
x=numinput("enter number between(3,5)","number",0,3,5)

if x ==5:
    tu.speed("fastest")
    tu.fillcolor('PINK')
    tu.begin_fill()
    for i in range (5):
        tu.circle(30,180)
        tu.rt(108)
    tu.end_fill()
    tu.up()
    tu.goto(-45,30)
    tu.down()
    tu.color('yellow')
    tu.dot(40)
    tu.rt(-90)
elif x==4:
    tu.speed("fastest")
    
    tu.fillcolor("#FAAFBE")
    tu.begin_fill()
    for i in range (4):
            tu.circle(40,180)
            tu.rt(90)
            # tu.fd(10)
    tu.end_fill()
    tu.up()
    tu.goto(-36,45)
    tu.down()
    tu.color('yellow')
    tu.dot(50)
    tu.rt(-90) 
    tu.up()
    tu.goto(-150,-200)
    tu.down()
    tu.pencolor("pink")
    
    tu.begin_fill()
    tu.color("pink")
    for i in range (4):
        tu.circle(110-i,90)
        tu.lt(90)
        tu.circle(110-i,90)
        tu.lt(9)
    tu.end_fill()

    # tu.pensize(10) 
    # tu.color("green") 
    # tu.rt(180)
    # tu.fd(70)
    # tu.down()
    # tu.fd(80) 
    # tu.lt(180)
elif x==3:
    tu.pencolor("pink")
    tu.screen.bgcolor("#e3f2fd")
    tu.speed("fastest")
    tu.begin_fill()
    tu.color("pink")
    for i in range (3):
        tu.circle(190-i,90)
        tu.lt(90)
        tu.circle(190-i,90)
        tu.lt(9)
    tu.end_fill()
    tu.up()
    tu.goto(0,-360)
    tu.down()
    tu.begin_fill()
    tu.color("pink")
    for i in range (1):
        tu.circle(190-i,90)
        tu.lt(90)
        tu.circle(190-i,90)
        tu.lt(9)
    tu.end_fill()
# else:
#         tu.write("enter num between 3,5",True,"center",["arial",40,"bold"])    
    
done()